/*
 *
 * TagContainer constants
 *
 */
export const FETCH_ARTICLES_TAGS = 'FETCH_ARTICLES_TAGS';
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS';
export const FETCH_TAGS_FAILURE = 'FETCH_TAGS_FAILURE';
export const FETCH_ARTICLES_TAG_SUCCESS = 'FETCH_ARTICLES_TAG_SUCCESS';
export const FETCH_ARTICLES_TAG_FAILURE = 'FETCH_ARTICLES_TAG_FAILURE';
