/*
 *
 * ArticleDetailContainer constants
 *
 */

export const RESET_ARTICLE = 'RESET_ARTICLE';
export const FETCH_ARTICLE_DETAIL = 'FETCH_ARTICLE_DETAIL';
export const FETCH_ARTICLE_DETAIL_SUCCESS = 'FETCH_ARTICLE_DETAIL_SUCCESS';
export const FETCH_ARTICLE_DETAIL_FAILURE = 'FETCH_ARTICLE_DETAIL_FAILURE';
