/*
 *
 * ArticleDetailContainer constants
 *
 */

export const RESET_ARTICLE = 'RESET_ARTICLE';
export const FETCH_ARTICLE_DETAIL = 'FETCH_ARTICLE_DETAIL';
export const FETCH_ARTICLE_DETAIL_SUCCESS = 'FETCH_ARTICLE_DETAIL_SUCCESS';
export const FETCH_ARTICLE_DETAIL_FAILURE = 'FETCH_ARTICLE_DETAIL_FAILURE';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';
export const RESET_COMMENTS = 'RESET_COMMENTS';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
