/*
 *
 * ProfileContainer constants
 *
 */

export const TOGGLE_FOLLOW = 'TOGGLE_FOLLOW';
export const FAVORITE_ARTICLE = 'FAVORITE_ARTICLE';
export const GET_PROFILE_BY_AUTHOR = 'GET_PROFILE_BY_AUTHOR';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';
export const GET_ARTICLES_BY_AUTHOR = 'GET_ARTICLES_BY_AUTHOR';
export const GET_ARTICLES_BY_AUTHOR_SUCCESS = 'GET_ARTICLES_BY_AUTHOR_SUCCESS';
export const GET_ARTICLES_BY_AUTHOR_FAILURE = 'GET_ARTICLES_BY_AUTHOR_FAILURE';
export const RESET_PROFILE_BY_AUTHOR = 'RESET_PROFILE_BY_AUTHOR';
export const RESET_ARTICLES_BY_AUTHOR = 'RESET_ARTICLES_BY_AUTHOR';
export const TOGGLE_ARTICLES_BY_AUTHOR = 'TOGGLE_ARTICLES_BY_AUTHOR';
export const TOGGLE_ARTICLES_SUCCESS = 'TOGGLE_ARTICLES_SUCCESS';