// constants
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const FETCH_ARTICLES_OFFSET_SUCCESS = 'FETCH_ARTICLES_OFFSET_SUCCESS';
export const FETCH_ARTICLES_OFFSET_FAILURE = 'FETCH_ARTICLES_OFFSET_FAILURE';