// constants
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const FETCH_ARTICLES_OFFSET_SUCCESS = 'FETCH_ARTICLES_OFFSET_SUCCESS';
export const FETCH_ARTICLES_OFFSET_FAILURE = 'FETCH_ARTICLES_OFFSET_FAILURE';
export const FETCH_ARTICLES_TAG_SUCCESS = 'FETCH_ARTICLES_TAG_SUCCESS';
export const FETCH_ARTICLES_TAG_FAILURE = 'FETCH_ARTICLES_TAG_FAILURE';
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS';
export const FETCH_TAGS_FAILURE = 'FETCH_TAGS_FAILURE';
export const FETCH_TAGS = 'FETCH_TAGS';
export const FETCH_DATA = 'FETCH_DATA';
export const GET_FEED_ARTICLES = 'GET_FEED_ARTICLES';
export const GET_FEED_ARTICLES_SUCCESS = 'GET_FEED_ARTICLES_SUCCESS';
export const GET_FEED_ARTICLES_FAILURE = 'GET_FEED_ARTICLES_FAILURE';
export const FETCH_ARTICLES_OFFSET = 'FETCH_ARTICLES_OFFSET';
export const FETCH_ARTICLES_TAGS = 'FETCH_ARTICLES_TAGS';
export const RESET_TAGNAME = 'RESET_TAGNAME';
export const FAVORITE_ARTICLE = 'FAVORITE_ARTICLE';
